### ISSUE TITLE
Bug: 获取课程信息失败

### ISSUE THREAD

**Issue by FrostN0v0** [csgo-adc/TencentClassDownloader#4]
## 描述问题

课程连接 `url = https://ke.qq.com/webcourse/476275/100570370`

环境及配置正常配置，能够获取到第一节课并下载，后续课程信息获取失败。

`{"result":{"header":{"code":13,"msg":"鉴权服务请求后台服务失败","ext_msg":""},"rec_video_info":null},"retcode":0}`

**Comment by csgo-adc** [comment]
可能是cookie设置的不对？还是没有买这个课程？我看第一节能下载是因为第一节免费的。
